# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'src/Parquet.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
#- task: UseDotNet@2
#  displayName: 'Install .NET Core SDK'
#  inputs:
#    version: 6.0.x
#    performMultiLevelLookup: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projectFile: '**/Parquet.csproj'
    feedsToUse: 'select'
    vstsFeed: '/3c5c1764-9633-49c7-8aae-7e8c3bc37469'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projectFile: '**/Parquet.csproj'
    arguments: '--no-restore'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: 'pack'
    packagesToPack: '**/Parquet.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: 'byPrereleaseNumber'

- task: DotNetCoreCLI@2
  displayName: 'dotnet push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '/3c5c1764-9633-49c7-8aae-7e8c3bc37469'
